### ISSUE TITLE
Demo Example

### ISSUE THREAD

**Issue by shukerullah** [react-native-china/react-native-animate-chart#3]
Proper demo project with all charts and features

**Comment by Obooman** [comment]
Hi my friend,I'll take my time to complete it,thank you for your attention

**Comment by kg-dogg** [comment]
Almost half year has passed, where is demo dude?

**Comment by Obooman** [comment]
[Here it is](https://github.com/react-native-china/react-native-animate-chart-demo) and sorry for my late responding.UPDATED README.
